onboarding = false

[ui.toast]
delivery = "herdr"

[theme]
name = "dracula"
auto_switch = false

[ui.sound]
enabled = true

[ui]
status_indicators = "dots"
copy_on_select = false

[terminal]
default_shell = "/usr/bin/zsh"
